defaults:
  - scope:
      path: "./optscatterplot.mjs"
      type: "text/javascript"
  - scope:
      path: "./d3-tip.mjs"
      type: "text/javascript"
  - scope:
      path: "./hideinput.mjs"
      type: "text/javascript"
  - scope:
      path: "./enablebouned.mjs"
      type: "text/javascript"
  - scope:
      path: "./random2.mjs"
      type: "text/javascript"
  - scope:
      path: "./objectivefunction.mjs"
      type: "text/javascript"
  - scope:
      path: "./fistmatrix2.mjs"
      type: "text/javascript"
  - scope:
      path: "./optimization.mjs"
      type: "text/javascript"
  - scope:
      path: "./optmatrix.mjs"
      type: "text/javascript"
  - scope:
      path: "./scatterplot.mjs"
      type: "text/javascript"
